
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Toshiba
 */
public class rezervsalon1 extends javax.swing.JDialog {
 DefaultTableModel model;


    public rezervsalon1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=( DefaultTableModel)jTable1.getModel();
        
    }

    private rezervsalon1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

     public ArrayList<salon1class> goster(){
      ArrayList<salon1class> goster=new  ArrayList<>();
       String host = "jdbc:mysql://localhost:3306/demo";
        String uName = "root";
        String uPass = "";
        try{
             Connection con = DriverManager.getConnection(host, uName, uPass);
            Statement stmt = con.createStatement();

            String sql = "SELECT * FROM salon1rezervasyon";
            ResultSet rs = stmt.executeQuery(sql);
            salon1class salon;
            while(rs.next()){
                salon=new salon1class(rs.getInt("id"),rs.getString("Ad"),rs.getString("Soyad"),rs.getString("Eposta"),rs.getString("Tarih"),rs.getDouble("Odeme"));
                goster.add(salon);
            }
            
        } catch(SQLException err){
          JOptionPane.showMessageDialog(null, "HATA");

        }
        return goster;
  }
  public void goster2(){
      ArrayList<salon1class> liste=goster();
      Object []row=new Object[6];
      for(int i=0;i<liste.size();i++){
          row[0]=liste.get(i).getId();
          row[1]=liste.get(i).getAd();
           row[2]=liste.get(i).getSoyad();
            row[3]=liste.get(i).getEposta();
          row[4]=liste.get(i).getTarih();
           row[5]=liste.get(i).getOdeme();
           model.addRow(row);
         
      }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ad", "Soyad", "Eposta", "Tarih", "Odeme"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("Müşteri Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void Ara(String ara){
    TableRowSorter<DefaultTableModel> tr=new TableRowSorter<>(model);
    jTable1.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(ara));
}
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String ara=jTextField1.getText();
        Ara(ara);
    }//GEN-LAST:event_jTextField1KeyReleased
public void sil(int id){
    String host = "jdbc:mysql://localhost:3306/demo";
        String uName = "root";
        String uPass = "";
        String sorgu="Delete from  salon1rezervasyon where id=?";
        try{
            Connection con = DriverManager.getConnection(host, uName, uPass);
            PreparedStatement stmt=con.prepareStatement(sorgu);
            stmt.setInt(1,id);
            stmt.executeUpdate();
            
        } catch(SQLException err){
                JOptionPane.showMessageDialog(null, "HATA");

}
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedrow=jTable1.getSelectedRow();
        if(selectedrow==-1){
            if(model.getRowCount()==0){
                System.out.println("tablo bos");
            }
            else{
                System.out.println("seciniz");
            }
        }    
        else{
           int id=(int) model.getValueAt(selectedrow, 0);
           sil(id);
          model.setRowCount(0);
           goster();
           goster2();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rezervsalon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rezervsalon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rezervsalon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rezervsalon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rezervsalon1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
