
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Toshiba
 */
public class teklif2 extends javax.swing.JFrame {

    /**
     * Creates new form teklif2
     */
    public teklif2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        posta = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        sayi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("E-posta:");

        jLabel4.setText("Telefon no:");

        jLabel5.setText("Düğün Tarihi:");

        jLabel7.setText("Davetli Sayısı:");

        jButton1.setText("Teklif Al");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ad)
                            .addComponent(soyad)
                            .addComponent(posta)
                            .addComponent(no)
                            .addComponent(sayi)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(posta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     String host = "jdbc:mysql://localhost:3306/demo";
     String uName = "root";
     String uPass= "";
         int fiyat;
        try {
      String adi=ad.getText();
      String soyadi=soyad.getText();
      String posta=this.posta.getText();
      String nosu=no.getText();
      SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyyy",Locale.getDefault());       
        String a=d.format(jDateChooser1.getDate());
        System.out.print(a);
      int davetli_sayisi= Integer.parseInt(sayi.getText());
        Connection con = DriverManager.getConnection(host,uName,uPass);
        Statement stmt = con.createStatement();
         String sql="SELECT * FROM  musteribilgiler WHERE Eposta='"+posta+"' ";
       ResultSet rs=stmt.executeQuery(sql);
        
           if(rs.next()){
               if(davetli_sayisi<250){
                    fiyat=7000;
                    int secim=JOptionPane.showConfirmDialog(this,"Fiyat "+fiyat+" onaylıyor musunuz?","confirm", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(secim==JOptionPane.YES_OPTION){
                        
                  try{
                      String Sorgu = "INSERT INTO salon1rezervasyon (Ad,Soyad,Eposta,Tarih,Odeme)VALUES (" + "'" + adi + "'," + "'" + soyadi+ "'," + "'" + posta+ "'," + "'" + a + "'," + "'" + fiyat + "')";
                       stmt.executeUpdate(Sorgu);
                       musteriekrani m=new musteriekrani();
                       m.setVisible(true);
                       
                  } catch(SQLException ex){
                       JOptionPane.showMessageDialog(null, "HATA");

                  }                                                                   
 
                       }                  
                   else if(secim==JOptionPane.NO_OPTION){
                        salon1 s=new salon1();
                        s.setVisible(true);
                }
                }
                else if(davetli_sayisi>250 && davetli_sayisi<400){
                    fiyat=9000;
                         int secim=JOptionPane.showConfirmDialog(this,"Fiyat "+fiyat+" onaylıyor musunuz?","confirm", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(secim==JOptionPane.YES_OPTION){
                        
                  try{
                      String Sorgu = "INSERT INTO salon1rezervasyon (Ad,Soyad,Eposta,Tarih,Odeme)VALUES (" + "'" + adi + "'," + "'" + soyadi+ "'," + "'" + posta+ "'," + "'" + a + "'," + "'" + fiyat + "')";
                       stmt.executeUpdate(Sorgu);
                        musteriekrani m=new musteriekrani();
                       m.setVisible(true);
                       
                  } catch(SQLException ex){
                       JOptionPane.showMessageDialog(null, "HATA");

                  }                                                                   
 
                       }                  
                   else if(secim==JOptionPane.NO_OPTION){
                        salon1 s=new salon1();
                        s.setVisible(true);
                }
                }
                else if(davetli_sayisi>400 && davetli_sayisi<500){
                    fiyat=10000;
                         int secim=JOptionPane.showConfirmDialog(this,"Fiyat "+fiyat+" onaylıyor musunuz?","confirm", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(secim==JOptionPane.YES_OPTION){
                        
                  try{
                      String Sorgu = "INSERT INTO salon1rezervasyon (Ad,Soyad,Eposta,Tarih,Odeme)VALUES (" + "'" + adi + "'," + "'" + soyadi+ "'," + "'" + posta+ "'," + "'" + a + "'," + "'" + fiyat + "')";
                       stmt.executeUpdate(Sorgu);
                        musteriekrani m=new musteriekrani();
                       m.setVisible(true);
                  } catch(SQLException ex){
                       JOptionPane.showMessageDialog(null, "HATA");

                  }                                                                   
                       }                  
                   else if(secim==JOptionPane.NO_OPTION){
                        salon1 s=new salon1();
                        s.setVisible(true);
                }
                }               
            }
            else{
                JOptionPane.showMessageDialog(null, "Böyle bir kullanıcı yok!!");
                 
                }
               
           
     }catch(SQLException err){
         JOptionPane.showMessageDialog(null, "HATA");
   
             
         }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teklif2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teklif2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teklif2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teklif2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teklif2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField no;
    private javax.swing.JTextField posta;
    private javax.swing.JTextField sayi;
    private javax.swing.JTextField soyad;
    // End of variables declaration//GEN-END:variables
}
